import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Authprovider from "./authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} h-full flex flex-col min-h-screen`}>
        <Authprovider>
          <Header />
          <section className="flex-1 mt-16 mb-24">{children}</section>
          <Footer />
        </Authprovider>
      </body>
    </html>
  );
}
